### ISSUE TITLE
Parameterisation for addtional electrode materials

### ISSUE THREAD

**Issue by jamiemfoster** [pybamm-team/PyBaMM#286] opened 2019-04-16 13:49 UTC
**Summary**
To input some additional chemical properties for different electrode materials

 **Motivation**
 Why are we doing this? What use cases does it support? What is the expected outcome?

**Additional context**

**Comment by tinosulzer** [comment] 2019-10-31 15:02
Duplicate of #675

**Closed by tinosulzer** 2019-10-31 15:02 UTC
