### ISSUE TITLE
Experiment termination[Bug]: 

### ISSUE THREAD

**Issue by Sourabh-Jadhav-2** [pybamm-team/PyBaMM#2251] opened 2022-08-22 08:35 UTC
### PyBaMM Version

22.5

### Python Version

3.8

### Describe the bug

I have calculated state of charge using initial SoC and discharge capacity. I want to terminate the experiment at 100% soc.

### Steps to Reproduce

use simple CCCV experiment and to plot soc, use  **initial soc - (discharge capacity / nominal capacity of cell) * 100**

**Comment by tinosulzer** [comment] 2022-08-22 08:51
Duplicate of #2103

**Closed by tinosulzer** 2022-08-22 08:51 UTC
Labels: bug
