### ISSUE TITLE
PyBaMM import error - Cannot run anything (import broken due to `pybtex`)

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#3940] opened 2024-03-28 12:50 UTC
### Discussed in https://github.com/pybamm-team/PyBaMM/discussions/3928

<div type='discussions-op-text'>

<sup>Originally posted by **abhishek-appana** March 25, 2024</sup>
Hello,

I am running Python 3.11.8 and installed PyBaMM 24.1 using pip on a Windows system. Earlier I was using Python 3.10 and everything was fine. But I am getting the below error after upgrading Python.

When I run `import pybamm`, it gives me the error:

ModuleNotFoundError: Optional dependency pybtex.database is not available. See https://docs.pybamm.org/en/latest/source/user_guide/installation/index.html#optional-dependencies for more details.

I tried installing pybamm using `pip install pybamm[all]`. I was still getting this error. How do I resolve this?</div>

<hr>

I think that this is a valid bug and it is still failing, and `import pybamm` should work without installing `pybamm[all]`. It can be noticed in the logs here: https://github.com/pybamm-team/PyBaMM/actions/runs/8461852686/job/23182296194, so I've converted this discussion to an issue instead (cc: @Saransh-cpp @arjxn-py). 

Perhaps this isn't being properly checked through #3892, @lorenzofavaro?

**Comment by agriyakhetarpal** [comment] 2024-03-28 13:02
Perhaps #3886 broke this where the try-catch blocks everywhere were removed? I haven't looked at this in enough detail, but the breakage is coming from this instantiation of the `Citations` class at the end of the file.

```python
citations = Citations()
```

where `__init__` tries to call the function `_reset()`, and that in-turn is trying to register the PyBaMM and NumPy citation, which will fail?

**Comment by Saransh-cpp** [comment] 2024-03-28 13:02
Hmm, I somehow can't reproduce this locally. I'm not sure where is this originating from.

**Comment by agriyakhetarpal** [comment] 2024-03-28 13:02
Me neither

**Comment by agriyakhetarpal** [comment] 2024-03-28 23:06
I haven't looked at this again, but I think having it fail in a fresh CI environment means there is indeed a bug, even if we can't reproduce it on our own machines. I added the "high priority" label for now.

Maybe a fix can be to register the PyBaMM and NumPy papers only inside the `print_citations()` method and only if they don't exist in the `_papers_to_cite` variable, so that they get cited when someone actually runs `pybamm.print_citations()`. I'm not sure if this is a complete fix, though.

**Comment by prady0t** [comment] 2024-03-29 11:46
Let me look into this.

**Comment by arjxn-py** [comment] 2024-04-01 14:35
I have looked into this and looks like this is failing as we merged #3932 & haven't removed the jobs to test `pybamm_install_odes`

**Comment by lorenzofavaro** [comment] 2024-04-05 15:33
I had a chance to look at the issue and understand the problem.

Actually at the moment pybamm has a hidden mandatory dependency, namely `pybtex` which is executed in `pybamm/citations.py:41` which in turn trigger `pybamm/citations.py:70`:
```python
parse_file = import_optional_dependency("pybtex.database", "parse_file")
```
During #3892 the error was still masked in `pybamm/citations` in the `except`:
```python
try:
  self.read_citations()
  self._reset()
except Exception as e:  # pragma: no cover
  self._citation_err_msg = e
```

Beyond that, the error was not reported after for a subtle issue.
The issue is that `test_pybamm_import` is done inside `tests/unit/test_util.py` which in turn is inside `tests/unit` and specifically if we look at the file `tests/unit/_init__.py` we find that it imports `StandardModelTest` which in turn imports `pybamm`.

When we don't have the external libraries installed locally (e.g., from local with `pybamm.[dev]`), this import avoid the tests execution during the `nox` session (it stops before), even though it reports them as `PASSED`. In fact, if you try to run the specific tests individually (i.e. `python -m unittest tests.unit.test_util.TestUtil.test_pybamm_import`), you would get an exception before the test run.

Instead, when we have external libraries installed (e.g. from CI with `pybamm.[all]`), we don't notice the error because digging deep into the `importlib` documentation, `importlib.reload(...)` does not reload all sub-modules.
So when it initially in `StandardModelTest` imports `pybamm`, it also imports `pybtex.database` which will no longer be imported even with the reload (not triggering the error we expect). To solve this, we should edit the `test_pybamm_import` function.

Possible solution steps:
1. Remove the hidden mandatory dependency from `pybtex` - I know that @prady0t is investigating to solve this.
2. Fix error detection - Edit `tests/unit/test_util.py`, in particular edit `test_pybamm_import`:
   - Do not use `importlib.reload(...)` to reload `pybamm`, instead remove `pybamm` from the `sys.modules` and all its sub-modules (so also `pybamm.citations` etc..).
   - In the `sys.modules` set to `None` all the optional modules (e.g. `pybtex`) and all their sub-modules (so also `pybtex.database`, etc..).

I could work on this in a shared PR with @prady0t.

**Comment by agriyakhetarpal** [comment] 2024-04-05 20:29
Thanks for posting this here, @lorenzofavaro, I think this is a reasonable solution based on our conversation earlier. You mentioned that you're working on some aspects of this too, so I'll assign you to this alongside @prady0t.

**Comment by prady0t** [comment] 2024-04-08 14:40
Hey @agriyakhetarpal, I won't be able to work on anything for at least a week due to a minor road accident. If @lorenzofavaro you are able to completely take care of this please go ahead.

**Comment by arjxn-py** [comment] 2024-04-08 14:47
Sorry to hear that @prady0t, Get well soon.
Don't worry as we'll be able to take care of this one.

**Comment by prady0t** [comment] 2024-04-08 20:11
Thanks a lot 🤗

**Closed** 2024-04-14 06:32 UTC
Labels: bug, priority: high
