### ISSUE TITLE
Track down and exclude non-deterministic benchmarks

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/PyBaMM#2954] opened 2023-05-15 18:28 UTC
Currently, several benchmarks pass or fail randomly on different runs. These benchmarks should be tracked and excluded to ensure the credibility of the remaining benchmarking suite.

Note: random regressions are okay because GH Actions can be a bit noisy sometimes, but solvers failing in a particular benchmark randomly should not be okay.

**Comment by jsbrittain** [comment] 2023-05-16 08:26
This sounds like a similar issue identified for integration tests due to random initial conditions, which was resolved by wrapping the `unittest` class to fix the random seeds across all tests; see #2844

**Comment by rtimms** [comment] 2023-05-16 08:49
These non-deterministic issues worry me. It comes from [perturbing the initial conditions in the casadi solver](https://github.com/pybamm-team/PyBaMM/blob/develop/pybamm/solvers/casadi_solver.py#L67), so we know why it happens, but I think for the user it is very unexpected behaviour. My vote would be to make this option `False` by default and suggest that users try setting it to `True` if the model struggles to get started. @tinosulzer, in your experience, how much difference did it make to the robustness of the solver?

**Comment by tinosulzer** [comment] 2023-05-16 16:39
It was really useful for avoiding errors at t=0 (`IDA_INIT` or something like that). But that was with casadi 3.5, so 3.6 might be more robust

**Comment by Saransh-cpp** [comment] 2023-06-09 17:43
I haven't been getting any time to work on this. I'll unassign myself and close the PR (which I don't think has something meaningful as of now). I'll pick it up again in a couple of weeks if it is still open by then.

**Comment by martinjrobins** [comment] 2023-06-12 15:56
suggestion from @brosaplanella: Looking at asv.conf.json, it seems we can specify different regression thresholds for various benchmarks (final lines of the json file): 

// "regressions_thresholds": {
  //    "some_benchmark": 0.01,     // Threshold of 1%
  //    "another_benchmark": 0.5,   // Threshold of 50%
  // },

Might be a way around it: tight thresholds for "unit" benchmarks, looser for "integration" benchmarks

**Comment by brosaplanella** [comment] 2023-06-12 15:59
> note that this particular test takes _waaaaay_ longer than the rest (when it succeeds)
> 
> ```
> False       ORegan2022    pybamm.solvers.casadi_solver.CasadiSolver   38.4±0.3s 
> ```

This is a quite tricky parameter set as it has the diffusion coefficient is very nonlinear. I would be happy to skip it the Casadi benchmark for it, or skip it altogether for the time being.

**Comment by martinjrobins** [comment] 2023-06-12 16:02
> > note that this particular test takes _waaaaay_ longer than the rest (when it succeeds)
> > ```
> > False       ORegan2022    pybamm.solvers.casadi_solver.CasadiSolver   38.4±0.3s 
> > ```
> 
> This is a quite tricky parameter set as it has the diffusion coefficient is very nonlinear. I would be happy to skip it the Casadi benchmark for it, or skip it altogether for the time being.
> 
> Also because it is likely the cause of why benchmarks take so long to solve...

I notice we're already skipping it for solve_first=true. We are also already using 30 particle grid points, so I'll turn it off fully for now

**Comment by martinjrobins** [comment] 2023-06-13 11:45
This benchmark is also occasionally timing out:

```
    GITT      Marquis2019   pybamm.models.full_battery_models.lithium_ion.dfn.DFN   pybamm.solvers.idaklu_solver.IDAKLUSolver   23.7±0.01s 
```

We do not do the corresponding benchmark for casadi (this has previously been turned off). Should we do the same for idaklu?

```
[ 95.00%] ··· time_sims_experiments.TimeSimulation.time_solve                 ok
[ 95.00%] ··· ============ ============= ======================================================= =========================================== ============
               experiment    parameter                         model_class                                       solver_class                            
              ------------ ------------- ------------------------------------------------------- ------------------------------------------- ------------
                  CCCV      Marquis2019   pybamm.models.full_battery_models.lithium_ion.spm.SPM   pybamm.solvers.casadi_solver.CasadiSolver   6.16±0.01s 
                  CCCV      Marquis2019   pybamm.models.full_battery_models.lithium_ion.spm.SPM   pybamm.solvers.idaklu_solver.IDAKLUSolver    6.19±0s   
                  CCCV      Marquis2019   pybamm.models.full_battery_models.lithium_ion.dfn.DFN   pybamm.solvers.casadi_solver.CasadiSolver    8.84±0s   
                  CCCV      Marquis2019   pybamm.models.full_battery_models.lithium_ion.dfn.DFN   pybamm.solvers.idaklu_solver.IDAKLUSolver   8.34±0.01s 
                  CCCV        Chen2020    pybamm.models.full_battery_models.lithium_ion.spm.SPM   pybamm.solvers.casadi_solver.CasadiSolver    2.77±0s   
                  CCCV        Chen2020    pybamm.models.full_battery_models.lithium_ion.spm.SPM   pybamm.solvers.idaklu_solver.IDAKLUSolver    2.78±0s   
                  CCCV        Chen2020    pybamm.models.full_battery_models.lithium_ion.dfn.DFN   pybamm.solvers.casadi_solver.CasadiSolver    5.54±0s   
                  CCCV        Chen2020    pybamm.models.full_battery_models.lithium_ion.dfn.DFN   pybamm.solvers.idaklu_solver.IDAKLUSolver    4.66±0s   
                  GITT      Marquis2019   pybamm.models.full_battery_models.lithium_ion.spm.SPM   pybamm.solvers.casadi_solver.CasadiSolver   20.2±0.01s 
                  GITT      Marquis2019   pybamm.models.full_battery_models.lithium_ion.spm.SPM   pybamm.solvers.idaklu_solver.IDAKLUSolver    20.4±0s   
                  GITT      Marquis2019   pybamm.models.full_battery_models.lithium_ion.dfn.DFN   pybamm.solvers.casadi_solver.CasadiSolver      n/a     
                  GITT      Marquis2019   pybamm.models.full_battery_models.lithium_ion.dfn.DFN   pybamm.solvers.idaklu_solver.IDAKLUSolver   23.7±0.01s 
                  GITT        Chen2020    pybamm.models.full_battery_models.lithium_ion.spm.SPM   pybamm.solvers.casadi_solver.CasadiSolver   7.59±0.01s 
                  GITT        Chen2020    pybamm.models.full_battery_models.lithium_ion.spm.SPM   pybamm.solvers.idaklu_solver.IDAKLUSolver    7.73±0s   
                  GITT        Chen2020    pybamm.models.full_battery_models.lithium_ion.dfn.DFN   pybamm.solvers.casadi_solver.CasadiSolver    12.9±0s   
                  GITT        Chen2020    pybamm.models.full_battery_models.lithium_ion.dfn.DFN   pybamm.solvers.idaklu_solver.IDAKLUSolver   11.0±0.01s 
              ============ ============= ======================================================= =========================================== ============
```

**Comment by martinjrobins** [comment] 2023-06-13 11:46
or I could increase the timeout if this benchmark is important

**Comment by brosaplanella** [comment] 2023-06-13 12:09
If it is GITT, maybe we can reduce the number of pulses tested. We currently do
```python3
"GITT": [("Discharge at C/20 for 1 hour", "Rest for 1 hour")] * 20,
```
so maybe we could do 10 pulses instead?

**Comment by Saransh-cpp** [comment] 2023-06-13 14:26
(Some of the non-deterministic benchmarks were excluded in #2784.)

**Closed** 2023-07-06 17:04 UTC
Labels: difficulty: easy, priority:high, in-progress
