### ISSUE TITLE
[Bug]: Voltage termination of drive cycle in experiment

### ISSUE THREAD

**Issue by WoohyunJeong95** [pybamm-team/PyBaMM#3693] opened 2024-01-08 06:32 UTC
### PyBaMM Version

23.9

### Python Version

3.11.5

### Describe the bug

![image](https://github.com/pybamm-team/PyBaMM/assets/155943778/68e25aa4-2baf-4cd1-b9f3-b46877ba126a)

I want to terminate drive cycle when voltage is below 3.6V, but the termination does not occur with this code. 

### Steps to Reproduce

model = pybamm.lithium_ion.SPM()
drive_cycle_current = pd.read_csv(
    "US06.csv", comment="#", header=None
).to_numpy()

experiment= pybamm.Experiment([pybamm.step.current(drive_cycle_current, termination="3.6V")])
sim = pybamm.Simulation(model,experiment=experiment)
sim.solve()
pybamm.dynamic_plot(sim.solution,output_variables=['Voltage [V]','Current [A]'])

**Comment by rtimms** [comment] 2024-01-08 10:07
Duplicate of https://github.com/pybamm-team/PyBaMM/issues/1902

**Closed by rtimms** 2024-01-08 10:07 UTC
Labels: bug
