### ISSUE TITLE
Replace `interp2d` in `ProcessedVariable`

### ISSUE THREAD

**Issue by rtimms** [pybamm-team/PyBaMM#2670] opened 2023-02-08 15:45 UTC
We currently use `interp2d` when creating processed variables, but this is deprecated. We should switch to `RegularGridInterpolator`.

```
DeprecationWarning: `interp2d` is deprecated!
`interp2d` is deprecated in SciPy 1.10 and will be removed in SciPy 1.12.0.

For legacy code, nearly bug-for-bug compatible replacements are
`RectBivariateSpline` on regular grids, and `bisplrep`/`bisplev` for
scattered 2D data.

In new code, for regular grids use `RegularGridInterpolator` instead.
For scattered data, prefer `LinearNDInterpolator` or
`CloughTocher2DInterpolator`.
```

**Comment by jeromtom** [comment] 2023-02-12 10:22
2. Alternative to interp2d: regular grid in the [transition guide](https://gist.github.com/ev-br/8544371b40f414b7eaf3fe6217209bff) is relevant to this.

**Comment by jaskiratsingh2000** [comment] 2023-02-19 18:25
HI @rtimms, and @jeromtom Can you let me know that where can I find the processed variable implementation fo "interp2d"? Thanks! :)

**Comment by rtimms** [comment] 2023-02-19 18:58
[Here](https://github.com/pybamm-team/PyBaMM/blob/12cbcff7fe0de9694b4be8e16e47038b729ecde9/pybamm/solvers/processed_variable.py#L630). There may be other places where it appears, so worth searching (e.g. doing ctrl+shift+f in vs code).

**Comment by jeromtom** [comment] 2023-02-19 18:59
It can be found here `pybamm\solvers\processed_variable.py`.

**Comment by jeromtom** [comment] 2023-02-19 19:13
Using [findstr](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/findstr)  and running `findstr /s /i interp2d *.*`  gives this
![image](https://user-images.githubusercontent.com/83979298/219969723-e71129e3-44a0-45d6-9b13-aead9b8dfbac.png)

8 mentions of `interp2d`, the first 4 in the documentation, and the last 4 in the code.

**Comment by tinosulzer** [comment] 2023-02-19 22:02
Sites in `sites-packages` are not part of documentation, they are installed dependencies.

I don't know what's in your `build` folder but it looks like it's a duplicate of the repository.

So ignore the first 6, it's only the last two

**Comment by jaskiratsingh2000** [comment] 2023-02-20 06:01
@rtimms , @jeromtom , and @tinosulzer Thanks for letting me know, I have made the changes as a part of pull request abiove. Could you please review it once? Thanks in Advance!

**Comment by arjxn-py** [comment] 2023-04-02 09:12
@rtimms If noone is working on this issue, I'd like to give it a try.

**Comment by rtimms** [comment] 2023-04-03 08:40
Hi @arjxn-py it looks like @jaskiratsingh2000 is no longer working on this, so feel free to pick it up. There is an open PR #2709 that may help. Thanks!

**Closed** 2023-04-30 14:47 UTC
Labels: difficulty: easy

**Comment by arjxn-py** [comment] 2023-04-30 14:57
Thanks @tinosulzer, I was really stuck at this.

**Comment by tinosulzer** [comment] 2023-04-30 15:41
Yeah it was getting a bit messy with all the different interpolants, switching to xarray made it much easier
