### ISSUE TITLE
Error when specifying both time and voltage limit in experiment: 

### ISSUE THREAD

**Issue by shwetankverma28** [pybamm-team/PyBaMM#2128] opened 2022-06-28 09:41 UTC
### PyBaMM Version

22.5

### Python Version

3.9.12 (Anaconda)

### Describe the bug

Hey everyone,
I am trying to run a drive cycle multiple times using pybamm.experiment. Here's the code that I am trying to run:
```
model = pybamm.lithium_ion.SPMe()

# remove voltage events from model
# alternatively, could change min/max voltage params
for event in model.events:
    if event.name == "Minimum voltage":
        model.events.remove(event)
for event in model.events:        
    if event.name == "Maximum voltage":    
        model.events.remove(event)    

# import drive cycle from file
drive_cycle_current = pd.read_csv(
    "pybamm/input/drive_cycles/US06.csv", comment="#", header=None
).to_numpy()


experiment = pybamm.Experiment(
    [
        (
            "Run US06_A (A) for 1 hour or until 2.5 V",
            "Charge at 0.5 C  until 4.1",
        ),
    ]
    * 2,
    drive_cycles={
        "US06_A": drive_cycle_current,
    },
)


sim = pybamm.Simulation(model, experiment=experiment, solver=pybamm.ScipySolver())
sim.solve()
sim.plot()
```

This gives the following error:

```
ValueError: too many values to unpack (expected 2)
```

Note that this does not happen when you run this experiment:
```
        (
            "Run US06_A (A)  until 2.5 V",
            "Charge at 0.5 C  for 2 hours until 4.1",
        )
```

### Steps to Reproduce

```
import pybamm
import pandas as pd

model = pybamm.lithium_ion.SPMe()

# import drive cycle from file
drive_cycle_current = pd.read_csv(
    "pybamm/input/drive_cycles/US06.csv", comment="#", header=None
).to_numpy()


experiment = pybamm.Experiment(
    [
        (
            "Run US06_A (A) for 1 hour or until 2.5 V",
            "Charge at 0.5 C  until 4.1",
        ),
    ]
    * 2,
    drive_cycles={
        "US06_A": drive_cycle_current,
    },
)


sim = pybamm.Simulation(model, experiment=experiment, solver=pybamm.ScipySolver())
sim.solve()
```

### Relevant log output

```shell
# import drive cycle from file
     13 drive_cycle_current = pd.read_csv(
     14     "US06.csv", comment="#", header=None
     15 ).to_numpy()
---> 18 experiment = pybamm.Experiment(
     19     [
     20         (
     21             "Run US06_A (A) for 1 hours or until 2.5 V ",
     22             "Charge at 0.5 C until 4.1 V",
     23         ),
     24     ]
     25     * 2,
     26     drive_cycles={
     27         "US06_A": drive_cycle_current,
     28     },
     29 )
     32 sim = pybamm.Simulation(model, experiment=experiment, solver=pybamm.ScipySolver())
...
--> 387     time, units = time_and_units
    388     if units in ["second", "seconds", "s", "sec"]:
    389         time_in_seconds = float(time)

ValueError: too many values to unpack (expected 2)
```

**Comment by tinosulzer** [comment] 2022-09-27 00:57
Duplicate of #1902

**Closed by tinosulzer** 2022-09-27 00:57 UTC
Labels: bug
